# Transport Switch vmknic IP Address Pool Details
nsxt_transport_switch_ip_pool_name: "{{ site_name }}-Pool"
nsxt_transport_switch_ip_pool_start: "192.168.140.101"
nsxt_transport_switch_ip_pool_end: "192.168.140.200"
nsxt_transport_switch_ip_pool_cidr: "192.168.140.0/24"
# Added by me
nsxt_transport_switch_ip_gateway: "192.168.140.1"