---
# tasks file for roles/nsxt_create_segments
- name: Create Segment
  vmware.ansible_for_nsxt.nsxt_policy_segment:
    hostname: "{{nsx_hostname}}"
    username: "{{nsx_username}}"
    password: "{{nsx_password}}"
    validate_certs: "{{ nsxt_validate_certs }}"
    state: present
    display_name: "{{segment.name}}"
    domain_name: "default"
    transport_zone_display_name: "{{segment.transportzone}}"
    replication_mode: "SOURCE"
#   advanced_config:
#     address_pool_display_name: small-2-pool
#     connectivity: "OFF"
#     hybrid: False
#     local_egress: True
    admin_state: UP
#   connectivity_path: "/infra/tier-1s/d082bc25-a9b2-4d13-afe5-d3cecad4b854"
    subnets:
      - gateway_address: "{{segment.gateway_address}}"

