---
## Deploys an NSX-T environment
- hosts: nsxmgr
  connection: local
  become: yes
  gather_facts: False
  vars_files:
    - nsx_config.yaml
- name: Create NSX-T IP Pools
  include: create_ip_pool.yml
  loop: "{{ ip_pools }}"
  loop_control:
    loop_var: ippool